name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    
      - name: Clean Repo
        run: |
          rm -rf actionstest
          
      - name: Clone Repo
        run: |
          git clone git@github.com:R0tt3nT0m4t0/actionstest.git
        
      - name: Build Image
        run: |
          cd actionstest
          podman build -t myimage:latest .

