name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build Image
        with:
          context: .
        run: |
          podman build -t myimage:latest .
