name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build Image
        run: |
          # podman build -t myimage:latest -f Containerfile
          podman build --runtime-flag debug .
